local anim_table = Flux.Anim:all()

anim_table.civil_protection = {
  normal = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE, ACT_IDLE_ANGRY_SMG1 },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_PISTOL_LOW, ACT_COVER_SMG1_LOW },
    [ACT_MP_WALK] = { ACT_WALK, ACT_WALK_AIM_RIFLE },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN, ACT_RUN_AIM_RIFLE },
    attack = ACT_GESTURE_RANGE_ATTACK_SMG1,
    glide = ACT_GLIDE
  },
  pistol = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE_PISTOL, ACT_IDLE_ANGRY_PISTOL },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_PISTOL_LOW, ACT_RANGE_AIM_PISTOL_LOW },
    [ACT_MP_WALK] = { ACT_WALK_PISTOL, ACT_WALK_AIM_PISTOL },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN_PISTOL, ACT_RUN_AIM_PISTOL },
    attack = ACT_GESTURE_RANGE_ATTACK_PISTOL,
    reload = ACT_RELOAD_PISTOL
  },
  smg = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE_SMG1, ACT_IDLE_ANGRY_SMG1 },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_SMG1_LOW, ACT_RANGE_AIM_SMG1_LOW },
    [ACT_MP_WALK] = { ACT_WALK_RIFLE, ACT_WALK_AIM_RIFLE },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN_RIFLE, ACT_RUN_AIM_RIFLE },
    attack = ACT_GESTURE_RANGE_ATTACK_SMG1,
    reload = ACT_GESTURE_RELOAD_SMG1
  },
  shotgun = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE_SMG1, ACT_IDLE_ANGRY_SMG1 },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_SMG1_LOW, ACT_RANGE_AIM_SMG1_LOW },
    [ACT_MP_WALK] = { ACT_WALK_RIFLE, ACT_WALK_AIM_RIFLE },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN_RIFLE, ACT_RUN_AIM_RIFLE },
    attack = ACT_GESTURE_RANGE_ATTACK_SMG1,
    reload = ACT_GESTURE_RELOAD_SMG1
  },
  grenade = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE, ACT_IDLE_ANGRY_MELEE },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_PISTOL_LOW, ACT_COVER_SMG1_LOW },
    [ACT_MP_WALK] = { ACT_WALK, ACT_WALK_ANGRY },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN, ACT_RUN },
    attack = ACT_RANGE_ATTACK_THROW
  },
  melee = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE, ACT_IDLE_ANGRY_MELEE },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_PISTOL_LOW, ACT_COVER_SMG1_LOW },
    [ACT_MP_WALK] = { ACT_WALK, ACT_WALK_ANGRY },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN, ACT_RUN },
    attack = ACT_MELEE_ATTACK_SWING
  },
  rpg = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE_SMG1, ACT_IDLE_ANGRY_SMG1 },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_SMG1_LOW, ACT_RANGE_AIM_SMG1_LOW },
    [ACT_MP_WALK] = { ACT_WALK_RIFLE, ACT_WALK_AIM_RIFLE },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN_RIFLE, ACT_RUN_AIM_RIFLE },
    attack = ACT_GESTURE_RANGE_ATTACK_SMG1,
    reload = ACT_GESTURE_RELOAD_SMG1
  },
  ar2 = {
    [ACT_MP_STAND_IDLE] = { ACT_IDLE_SMG1, ACT_IDLE_ANGRY_SMG1 },
    [ACT_MP_CROUCH_IDLE] = { ACT_COVER_SMG1_LOW, ACT_RANGE_AIM_SMG1_LOW },
    [ACT_MP_WALK] = { ACT_WALK_RIFLE, ACT_WALK_AIM_RIFLE },
    [ACT_MP_CROUCHWALK] = { ACT_WALK_CROUCH, ACT_WALK_CROUCH },
    [ACT_MP_RUN] = { ACT_RUN_RIFLE, ACT_RUN_AIM_RIFLE },
    attack = ACT_GESTURE_RANGE_ATTACK_SMG1,
    reload = ACT_GESTURE_RELOAD_SMG1
  },
  vehicle = {
    prop_vehicle_prisoner_pod = { ACT_IDLE, Vector(0, 0, 0) },
    prop_vehicle_jeep = { ACT_COVER_SMG1_LOW, Vector(15, 0, 0) },
    prop_vehicle_airboat = { ACT_COVER_SMG1_LOW, Vector(10, 0, -5) }
  }
}

anim_table.ota = {
  normal = {
		[ACT_MP_STAND_IDLE] = {ACT_IDLE, ACT_IDLE_ANGRY},
		[ACT_MP_CROUCH_IDLE] = {ACT_CROUCHIDLE, ACT_CROUCHIDLE},
		[ACT_MP_WALK] = {ACT_WALK_RIFLE, ACT_WALK_AIM_RIFLE},
		[ACT_MP_CROUCHWALK] = {ACT_WALK_CROUCH_RIFLE, ACT_WALK_CROUCH_RIFLE},
		[ACT_MP_RUN] = {ACT_RUN_AIM_RIFLE, ACT_RUN_AIM_RIFLE},
		[ACT_LAND] = {ACT_RESET, ACT_RESET}
	},
	pistol = {
		[ACT_MP_STAND_IDLE] = {ACT_IDLE, ACT_IDLE_ANGRY_SMG1},
		[ACT_MP_CROUCH_IDLE] = {ACT_CROUCHIDLE, ACT_CROUCHIDLE},
		[ACT_MP_WALK] = {ACT_WALK_RIFLE, ACT_WALK_RIFLE},
		[ACT_MP_CROUCHWALK] = {ACT_WALK_CROUCH_RIFLE, ACT_WALK_CROUCH_RIFLE},
		[ACT_MP_RUN] = {ACT_RUN_AIM_RIFLE, ACT_RUN_AIM_RIFLE},
		[ACT_LAND] = {ACT_RESET, ACT_RESET}
	},
	smg = {
		[ACT_MP_STAND_IDLE] = {ACT_IDLE_SMG1, ACT_IDLE_ANGRY_SMG1},
		[ACT_MP_CROUCH_IDLE] = {ACT_CROUCHIDLE, ACT_CROUCHIDLE},
		[ACT_MP_WALK] = {ACT_WALK_RIFLE, ACT_WALK_AIM_RIFLE},
		[ACT_MP_CROUCHWALK] = {ACT_WALK_CROUCH_RIFLE, ACT_WALK_CROUCH_RIFLE},
		[ACT_MP_RUN] = {ACT_RUN_RIFLE, ACT_RUN_AIM_RIFLE},
		[ACT_LAND] = {ACT_RESET, ACT_RESET}
	},
	shotgun = {
		[ACT_MP_STAND_IDLE] = {ACT_IDLE_SMG1, ACT_IDLE_ANGRY_SHOTGUN},
		[ACT_MP_CROUCH_IDLE] = {ACT_CROUCHIDLE, ACT_CROUCHIDLE},
		[ACT_MP_WALK] = {ACT_WALK_RIFLE, ACT_WALK_AIM_SHOTGUN},
		[ACT_MP_CROUCHWALK] = {ACT_WALK_CROUCH_RIFLE, ACT_WALK_CROUCH_RIFLE},
		[ACT_MP_RUN] = {ACT_RUN_RIFLE, ACT_RUN_AIM_SHOTGUN},
		[ACT_LAND] = {ACT_RESET, ACT_RESET}
	},
	grenade = {
		[ACT_MP_STAND_IDLE] = {ACT_IDLE, ACT_IDLE_ANGRY},
		[ACT_MP_CROUCH_IDLE] = {ACT_CROUCHIDLE, ACT_CROUCHIDLE},
		[ACT_MP_WALK] = {ACT_WALK_RIFLE, ACT_WALK_RIFLE},
		[ACT_MP_CROUCHWALK] = {ACT_WALK_CROUCH_RIFLE, ACT_WALK_CROUCH_RIFLE},
		[ACT_MP_RUN] = {ACT_RUN_AIM_RIFLE, ACT_RUN_AIM_RIFLE},
		[ACT_LAND] = {ACT_RESET, ACT_RESET}
	},
	melee = {
		[ACT_MP_STAND_IDLE] = {ACT_IDLE, ACT_IDLE_ANGRY},
		[ACT_MP_CROUCH_IDLE] = {ACT_CROUCHIDLE, ACT_CROUCHIDLE},
		[ACT_MP_WALK] = {ACT_WALK_RIFLE, ACT_WALK_RIFLE},
		[ACT_MP_CROUCHWALK] = {ACT_WALK_CROUCH_RIFLE, ACT_WALK_CROUCH_RIFLE},
		[ACT_MP_RUN] = {ACT_RUN_AIM_RIFLE, ACT_RUN_AIM_RIFLE},
		[ACT_LAND] = {ACT_RESET, ACT_RESET},
		attack = ACT_MELEE_ATTACK_SWING_GESTURE
	},
	glide = ACT_GLIDE
}
